name: Automated_tests


on:
  workflow_dispatch:
    inputs:
      deployment_target:
        description: Choose target
        required: true
        default:
        type: choice
        options:
          - login_page
          - product_page

jobs:
  tests:
    runs-on: ubuntu-latest


    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - name: Download Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: install Chrome
        run: sudo apt-get install google-chrome-stable
      - name: install Modules from requirements.txt
        run: pip install -r requirements.txt
      - name: Install playwright
        run: playwright install
      - name: Tests for login page
        if: "github.event.inputs.deployment_target == 'login_page'"
        run: python -m pytest tests/test_login_page.py
      - name: Tests for Product page
        if: "github.event.inputs.deployment_target == 'product_page'"
        run: python -m pytest tests/test_product_page.py