name: Automated_tests


on:
  workflow_dispatch:
    inputs:
      deployment_target:
        description: Choose target
        required: true
        default:
        type: choice
        options:
          - login_page
          - product_page

jobs:
  tests:
    runs-on: ubuntu-latest


    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - name: Download Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: install Chrome
        run: sudo apt-get install google-chrome-stable
      - name: Install Allure
        run: |
          sudo apt update
          sudo apt install -y openjdk-11-jdk
          wget https://github.com/allure-framework/allure2/releases/download/2.24.0/allure-2.24.0.tgz
          tar -xzf allure-2.24.0.tgz
          sudo mv allure-2.24.0 /opt/allure
          sudo ln -s /opt/allure/bin/allure /usr/bin/allure
      - name: install Modules from requirements.txt
        run: pip install -r requirements.txt
      - name: Install playwright
        run: playwright install
      - name: Tests for login page
        if: "github.event.inputs.deployment_target == 'login_page'"
        run: python -m pytest tests/test_login_page.py --alluredir=allure-results
      - name: Tests for Product page
        if: "github.event.inputs.deployment_target == 'product_page'"
        run: python -m pytest tests/test_product_page.py --alluredir=allure-results

      - name: Generate Allure report
        run: allure generate allure-results --clean -o allure-report

      - name: Upload Allure report
        uses: actions/upload-artifact@v3
        with:
          name: allure-report
          path: allure-report
